### ISSUE TITLE
 ridge/lasso regression with non -negative coefficients when data is sparse one hot data

### ISSUE THREAD

**Issue by Sandy4321** [RoyiAvital/StackExchangeCodes#5]
great code
but do you have code for ridge/lasso regression with non -negative coefficients
when data is sparse one hot data and data matrix is very big?
for example data matrix is

1  0 0 0 1
0 1 0  1 0
0 0 0  1  1
etc 

for example for FISTA solver?

**Comment by RoyiAvital** [comment]
Please open a question on [Signal Processing Stack Exchange](https://dsp.stackexchange.com/), link it here and I will answer it.

**Comment by Sandy4321** [comment]
sure
done
link is
https://dsp.stackexchange.com/questions/77048/plain-python-numpy-code-for-ridge-lasso-regression-with-non-negative-coefficient

**Comment by RoyiAvital** [comment]
The question in the link isn't what's you asked above.

If you ask how to solve $ \frac{1}{2} {\left\| A x - b \right\|}_{2}^{2} + \lambda {\left\| x \right\|}_{1} $ subject to $ {x]_{i} \geq 0 $ then I can help and it is a valid question.

**Comment by Sandy4321** [comment]
yes 
this optimization is part of question 
is there some specific if data is sparse and values are 0s and 1s - one  hot data?

**Comment by Sandy4321** [comment]
do you want me to create new question exactly like
$ \frac{1}{2} {\left| A x - b \right|}{2}^{2} + \lambda {\left| x \right|}{1} $ subject to $ {x]_{i} \geq 0 $ 
?

**Comment by Sandy4321** [comment]
in any case I created new question
https://dsp.stackexchange.com/questions/78077/plain-python-code-for-ridge-lasso-multivariate-regression-for-non-negative-coeff

Thanks
